export const textPrompt = [
  "Craft an epic portrait, optimized to Twitter Profile picture aspect ratio, showcasing an adorable animated-male-baby-fox in a Pixar style.",
  "Create an epic portrait with a Disney style, optimized to Twitter Profile picture aspect ratio, featuring an adorable animated-male-baby-fox.",
  "Develop an epic portrait, optimized to Twitter Profile picture aspect ratio, capturing the charm of an adorable animated-male-baby-fox in a Looney-Tunes style.",
  "Generate an epic portrait, featuring an adorable animated-male-baby-fox, with a Pixar style that is optimized to Twitter Profile picture aspect ratio.",
  "Produce an epic portrait in a Disney style, optimized to Twitter Profile picture aspect ratio, showcasing the irresistible appeal of an adorable animated-male-baby-fox.",
  "Design an epic portrait, optimized to Twitter Profile picture aspect ratio, presenting an adorable animated-male-baby-fox in a Looney-Tunes style.",
  "Illustrate an epic portrait with a Disney style, featuring an adorable animated-male-baby-fox, optimized to Twitter Profile picture aspect ratio.",
  "Craft an epic portrait, capturing the essence of an adorable animated-male-baby-fox, in a Pixar style optimized to Twitter Profile picture aspect ratio.",
  "Create an epic portrait in a Disney style, optimized to Twitter Profile picture aspect ratio, portraying the lovable animated-male-baby-fox.",
  "Develop an epic portrait, featuring an adorable animated-male-baby-fox, with a Pixar style that is optimized to Twitter Profile picture aspect ratio.",
  "Generate an epic portrait in a Pixar style, optimized to Twitter Profile picture aspect ratio, showcasing the delightful animated-male-baby-fox.",
  "Produce an epic portrait, optimized to Twitter Profile picture aspect ratio, presenting an adorable animated-male-baby-fox in a Looney-Tunes style.",
  "Design an epic portrait with a Pixar style, featuring an adorable animated-male-baby-fox, optimized to Twitter Profile picture aspect ratio.",
  "Illustrate an epic portrait, capturing the captivating charm of an adorable animated-male-baby-fox, in a Disney style optimized to Twitter Profile picture aspect ratio.",
  "Craft an epic portrait in a Looney-Tunes style, optimized to Twitter Profile picture aspect ratio, showcasing the irresistible animated-male-baby-fox.",
  "Create an epic portrait, featuring an adorable animated-male-baby-fox, with a Disney style that is optimized to Twitter Profile picture aspect ratio.",
  "Develop an epic portrait in a Pixar style, optimized to Twitter Profile picture aspect ratio, portraying the endearing animated-male-baby-fox.",
  "Generate an epic portrait, optimized to Twitter Profile picture aspect ratio, presenting an adorable animated-male-baby-fox in a Disney style.",
  "Produce an epic portrait with a Looney-Tunes style, featuring an adorable animated-male-baby-fox, optimized to Twitter Profile picture aspect ratio.",
  "Design an epic portrait, capturing the essence of an adorable animated-male-baby-fox, in a Pixar style optimized to Twitter Profile picture aspect ratio.",
];
